spring:
  application:
    name: BuildMate
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.coding shuttle: DEBUG       # your package logs
    org.hibernate.SQL: DEBUG       # log SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # log SQL parameters

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90hsdfbasdhji8qiqijvlckajdl

stripe:
  api:
    secret: sk_test_51SshBDFGdm9EFHC1zemThbfrvitICSu07Uof3K5kGp2uA01bWUApuInR4y9CxV9Ji4Pmb6CPMD0fDOHamtkeHA8M00VbYUqcVs
  webhook:
    secret: whsec_fda5e4a20d736fbd010c9132794e4ade35d6f3534ee72864984b3fb0b67dbc40

client.url: http://localhost:8080